//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int ID { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public int KPP { get; set; }
        public int WheelDrive { get; set; }
        public decimal Power { get; set; }
        public decimal Volume { get; set; }
        public int Color { get; set; }
        public string Photo { get; set; }
        public int Cost { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual ColorTable ColorTable { get; set; }
        public virtual KPPTable KPPTable { get; set; }
        public virtual WheelDriveTable WheelDriveTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }

        public string CarKPP
        {
            get
            {
                return KPPTable.KPP;
            }
        }

        public string CarWheelDrive
        {
            get
            {
                return WheelDriveTable.WheelDrive;
            }
        }

        public string CarColor
        {
            get
            {
                return ColorTable.Color;
            }
        }

    }


}
