//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public int ClientID { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }

        public string ColorSale
        {
            get
            {
                return Cars.CarColor;
            }
        }
    }
}
