//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public int ClientID { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }

        public string CarMake
        {
            get
            {
                return Cars.CarMake;
            }
        }
        public string Model
        {
            get
            {
                return Cars.Model;
            }
        }
        public decimal Power
        {
            get
            {
                return Cars.Power;
            }
        }
        public decimal Volume
        {
            get
            {
                return Cars.Volume;
            }
        }
        public int Cost
        {
            get
            {
                return Cars.Cost;
            }
        }
        public string Photo
        {
            get
            {
                return Cars.Photo;
            }
        }
        public string CarColor
        {
            get
            {
                return Cars.CarColor;
            }
        }
        public string CarKPP
        {
            get
            {
                return Cars.CarKPP;
            }
        }
        public string CarWheelDrive
        {
            get {
                return Cars.CarWheelDrive;
            }
        }
        public string Name
        {
            get
            {
                return Clients.Firstname;
            }
        }
        public string Surname
        {
            get
            {
                return Clients.Surname;
            }
        }
        public string Patronymic
        {
            get
            {
                return Clients.Patronymic;
            }
        }
    }
}
